app/ws/chebi_workflow.py

adding change to remove hydrogens

adding function to remove hydrogen

---

app/ws/chebi_workflow.py

Exclude chem spider ID from COMMENT field

 updated for COMMENT - does not include chem spider ID

---

app/ws/chebi_workflow.py

run of cluster - job param parsing done

Chebi pipeline

---

app/ws/chebi_workflow.py

run on cluster fix- update in cluster curl command

---

app/ws/cronjob.py
app/ws/reports.py
app/ws/utils.py
requirements.txt

fix for sync issue

---

app/ws/organism.py

Fixing issue with Organism get service

Metlight 3072

---

app/ws/pathway.py

- quick fix kegg_only default value
- change data template

chebi-kegg quick fix

---

app/ws/cronjob.py

- automatic update species info to curation log

---

app/ws/cronjob.py

Add ftp folder access permission check to cronjob
submitted - 770, 
curation - 750,
review - 550

- add ftp folder permission check to cronjob endpoint

---

app/ws/ontology.py
app/ws/organism.py

update placeholder endpoint to make organism corrections

Placeholder

---

app/ws/mtblsStudy.py
app/ws/study_utilities.py
app/ws/utils.py

Merging into development first then doing a formal release to master (hopefully)

Metlight 4355 soft delete

---

app/ws/study_files.py
config.py
wsapp.py

Files-fetch API for reducing processing of server

Files fetch

---

app/ws/validation.py

Added new validation 'rule' that accepts text files in the derived column in the event of a valid corresponding raw file in the raw column. I also added some method level comments, some comments in the code, changed some variable names and removed some commented out code in order to make the code more readable.

Metlight 4339 assay validation rule

---

config.py

Add .mgf to DERIVED files list

---

app/ws/validation.py

request from pamela, very small change

Output missing files to text

---

app/ws/isaApiClient.py
app/ws/misc_utilities/file_utilities.py
app/ws/misc_utilities/request_parsers.py
app/ws/report_builders/europe_pmc_builder.py
app/ws/reports.py
app/ws/study_files.py
app/ws/validation.py
requirements.txt
scripts/cross_reference_study_statuses.py
wsapp.py

Merging development into master

Development merge March 16 2022

---

app/ws/ontology.py

fix bug where we couldn't add new entities due to incorrectly checking the starts of individual entries

fix bug in addEntity Ontology

---

app/ws/db/wrappers.py
app/ws/ontology_info.py
app/ws/study/validation/commons.py
resources/mzML1.1.0.xsd
resources/mzML1.1.1_idx.xsd

Quick fixes on Master

---

app/ws/db/models.py
app/ws/db/wrappers.py
app/ws/mtblsStudy.py
app/wsapp_config.py

Java public study details endpoint is migrated to python. Path endpoint is /metabolights/ws/public/study/<study_id>

MTBLS-121-study detail java endpoint is moved to python

---

app/ws/auth/auth_manager.py
app/ws/auth/authentication.py
app/wsapp_config.py

endpoint is /ws/auth/login-with-token
Returns jwt token in header if it is valid user
input format 
{ "token": "user token",  
"user": { "userName": "user email address" } 
}

MTBLS-203 New auth api that authenticates user with api token and username

---

app/ws/chebi_workflow.py

Enable Chebi annotation folder creation disabled after FTP change

---

app/services/storage_service/mounted/local_storage.py
app/services/storage_service/storage.py
app/services/storage_service/storage_service.py
app/services/storage_service/unmounted/data_mover_client.py
app/services/storage_service/unmounted/unmounted_storage.py
app/ws/ftp/ftp_operations.py
app/wsapp_config.py
config.py

Implement Public study sync to FTP API

---

app/ws/send_files.py

Comma separator issue in download API

Fix download API issue of comma separator

---

app/ws/chebi_workflow.py

Fix - DimeDB timeout , try handle API hits , status of the APIs hits

---

app/ws/chebi_workflow.py

Added classyfire SDF file status

Add status for classyfire SDF file

---

app/ws/chebi_workflow.py

Move API checking to separate methods

Check CHEBI pipeline APIs in separate methods

---

app/ws/chebi_workflow.py

Process all unichem response and output

Process all DB accessions of Unichem response

---

app/ws/chebi_workflow.py

Scrape DB names from Unichem API response

---

app/ws/chebi_workflow.py

Chebi pipe issue

---

app/ws/cluster_jobs.py

Fix default job running time widnow in codon cluster

---

app/ws/cluster_jobs.py

Make Job running window time as 24hrs

---

app/ws/tasks/twitter.py

Twitter v2

---

app/ws/chebi_workflow.py

Add Chebi Master List check in Pipeline result

---

app/tasks/bash_client.py
app/tasks/common_tasks/basic_tasks/execute_commands.py
app/tasks/common_tasks/curation_tasks/chebi_pipeline.py
app/tasks/datamover_tasks/basic_tasks/execute_commands.py
app/tasks/hpc_rsync_worker.py
app/tasks/worker.py
app/ws/chebi_pipeline_utils.py
app/ws/chebi_workflow.py
app/ws/mtblsWSclient.py
app/wsapp_config.py

Chebi pipeline code moved to Celery worker

Chebi pipeline worker conversion

---

app/ws/isaAssay.py
app/ws/isaStudy.py
app/ws/study/validation/commons.py
app/ws/utils.py
resources/validation_schema.json

Update Validation rules

---

app/ws/db/models.py

Pydantic ORM update

---

app/ws/settings/base.py
app/ws/study_folder_utils.py

Pydantic from_attribute

---

app/ws/db/models.py

Fix study model validation error

Fix study model validation error

---

app/ws/db/models.py
app/ws/db/schemes.py
app/ws/study/user_service.py
scripts/add_partner_column_to_users_table.sql

Some submitters can create multiple studies.

partner column added into users table.

---

app/tasks/common_tasks/basic_tasks/email.py
app/ws/email/email_service.py
app/ws/email/email_templates/new_accession_number.html
app/ws/email/email_templates/status_is_public.html
app/ws/study_actions.py

fix typos in email templates, add user email address into cc if user is not submitter.

Add Principal Investigator email addresses into cc

---

app/ws/table_editor.py

(as in the case of adding a factor + unit) was erroring

fixed issue where adding more than three columns 

---

app/ws/study/study_revision_service.py
app/ws/study_actions.py

Curators and submitters can not update public study status.

New workflow do not change public status

---

app/services/cluster/slurm_client.py
app/ws/compress.py
app/ws/study_files.py
resources/templates/scripts/compress_raw_data_folders.sh.j2

Some fixes and refactor 
retry if HPC submission is failed.
compress script is updated. 
FTP files-fetch endpoints result will be sorted

compress folder endpoint updates

---

app/ws/cronjob.py

Staging merge first private date

Staging merge first private date
